/** Engine tests only. Not imported by the client. */
import type { Fill, Position } from "../src/data/fixture";
import type { Launch } from "../src/lib/setups";

export const SAMPLE_CASH_XCP = 14;
export const SAMPLE_TIP_BLOCK = 964404;

export const SAMPLE_POSITIONS: Position[] = [
  {
    asset: "XCP",
    kind: "cash",
    qty: 14,
    priceXcp: 1,
    markXcp: 14,
    costXcp: 14,
    pnlXcp: 0,
    pnlPct: 0,
  },
  {
    asset: "SAMPLEALPHA",
    kind: "token",
    qty: 150_000,
    priceXcp: 0.0000118666666667,
    markXcp: 1.78,
    costXcp: 2,
    pnlXcp: -0.22,
    pnlPct: -11,
  },
  {
    asset: "SAMPLEBETA",
    kind: "token",
    qty: 60_000,
    priceXcp: 0.0000155,
    markXcp: 0.93,
    costXcp: 1,
    pnlXcp: -0.07,
    pnlPct: -7,
  },
  {
    asset: "SAMPLEGAMMA",
    kind: "token",
    qty: 50_000,
    priceXcp: 0.0000186,
    markXcp: 0.93,
    costXcp: 1,
    pnlXcp: -0.07,
    pnlPct: -7,
  },
  {
    asset: "SAMPLEDELTA",
    kind: "token",
    qty: 40_000,
    priceXcp: 0.000018,
    markXcp: 0.72,
    costXcp: 0.44,
    pnlXcp: 0.28,
    pnlPct: 63.64,
  },
  {
    asset: "SAMPLEESCROW",
    kind: "escrow",
    qty: 200_000,
    priceXcp: 0.00001,
    markXcp: 2,
    costXcp: 2,
    pnlXcp: 0,
    pnlPct: 0,
  },
];

export const SAMPLE_FILLS: Fill[] = [
  {
    id: "dispense",
    block: 964_337,
    time: "27 Aug 22:14",
    action: "contribution",
    asset: "XCP",
    detail: "Dispenser credit",
    xcp: 20,
  },
  {
    id: "delta-buy",
    block: 964_339,
    time: "27 Aug 22:31",
    action: "buy",
    asset: "SAMPLEDELTA",
    detail: "100,000 SAMPLEDELTA · pool",
    xcp: -1,
    qty: 100_000,
  },
  {
    id: "delta-sell",
    block: 964_399,
    time: "28 Aug 08:59",
    action: "sell",
    asset: "SAMPLEDELTA",
    detail: "60,000 SAMPLEDELTA · pool",
    xcp: 1,
    qty: 60_000,
  },
  {
    id: "escrow-mint",
    block: 964_400,
    time: "28 Aug 09:20",
    action: "mint_escrow",
    asset: "SAMPLEESCROW",
    detail: "200,000 SAMPLEESCROW · escrow",
    xcp: -2,
    qty: 200_000,
  },
  {
    id: "alpha-buy",
    block: 964_400,
    time: "28 Aug 09:20",
    action: "buy",
    asset: "SAMPLEALPHA",
    detail: "150,000 SAMPLEALPHA · pool",
    xcp: -2,
    qty: 150_000,
  },
  {
    id: "beta-buy",
    block: 964_400,
    time: "28 Aug 09:20",
    action: "buy",
    asset: "SAMPLEBETA",
    detail: "60,000 SAMPLEBETA · pool",
    xcp: -1,
    qty: 60_000,
  },
  {
    id: "gamma-buy",
    block: 964_400,
    time: "28 Aug 09:20",
    action: "buy",
    asset: "SAMPLEGAMMA",
    detail: "50,000 SAMPLEGAMMA · pool",
    xcp: -1,
    qty: 50_000,
  },
];

function row(
  launch: Omit<Launch, "issuer"> & { issuer?: string },
): Launch {
  return { issuer: "unknown", ...launch };
}

export const SAMPLE_UNIVERSE: Launch[] = [
  row({
    asset: "SAMPLEDEEP",
    status: "graduated",
    mark: 0.00012,
    poolXcp: 800,
    fill: 1,
    blocksLeft: null,
    blocksSinceOpen: 200,
    you: "none",
    youSleeveWt: 0,
    youMintPaidXcp: 0,
  }),
  row({
    asset: "SAMPLEPEER",
    status: "graduated",
    mark: 0.00004,
    poolXcp: 500,
    fill: 1,
    blocksLeft: null,
    blocksSinceOpen: 180,
    you: "none",
    youSleeveWt: 0,
    youMintPaidXcp: 0,
  }),
  row({
    asset: "SAMPLESIBLING",
    status: "graduated",
    mark: 0.00003,
    poolXcp: 450,
    fill: 1,
    blocksLeft: null,
    blocksSinceOpen: 180,
    you: "none",
    youSleeveWt: 0,
    youMintPaidXcp: 0,
  }),
  row({
    asset: "SAMPLEGAMMA",
    status: "graduated",
    mark: 0.00001864,
    poolXcp: 633.35,
    fill: 1,
    blocksLeft: null,
    blocksSinceOpen: 4,
    you: "held",
    youSleeveWt: 0.209,
    youMintPaidXcp: 0,
  }),
  row({
    asset: "SAMPLEDELTA",
    status: "graduated",
    mark: 0.00001781,
    poolXcp: 618.89,
    fill: 1,
    blocksLeft: null,
    blocksSinceOpen: 1,
    you: "held",
    youSleeveWt: 0.164,
    youMintPaidXcp: 0,
  }),
  row({
    asset: "SAMPLEBETA",
    status: "graduated",
    mark: 0.00001546,
    poolXcp: 576.23,
    fill: 1,
    blocksLeft: null,
    blocksSinceOpen: 3,
    you: "held",
    youSleeveWt: 0.209,
    youMintPaidXcp: 0,
  }),
  row({
    asset: "SAMPLEALPHA",
    status: "graduated",
    mark: 0.00001189,
    poolXcp: 510.94,
    fill: 1,
    blocksLeft: null,
    blocksSinceOpen: 1,
    you: "held",
    youSleeveWt: 0.419,
    youMintPaidXcp: 0,
  }),
  row({
    asset: "SAMPLEESCROW",
    status: "minting",
    mark: null,
    poolXcp: null,
    fill: 0.078,
    blocksLeft: 974,
    blocksSinceOpen: null,
    you: "escrow",
    youSleeveWt: 0,
    youMintPaidXcp: 2,
  }),
];

export const SAMPLE_IMPACT_BY_ASSET: Record<string, number> = Object.fromEntries(
  SAMPLE_UNIVERSE.filter((l) => l.mark != null).map((l) => [l.asset, 0.04]),
);
